TEXTS_FOLDER: str = 'texts'
WARNING_TIME: float = 1

DEFAULT_COLOR: str = 'white'

RIGHT_LETTER_COLOR: str = 'green'
WRONG_LETTER_COLOR: str = 'red'
RIGHT_WITH_MISTAKE_LETTER_COLOR: str = 'yellow'

IMPORTANT_INFORMATION_COLOR: str = 'green'
BAD_INFORMATION_COLOR: str = 'red'

OUTPUT_SYMBOL: str = '`'

MAX_LINE_LENGTH: int = 80

PROGRESS_BAR_LENGTH: int = 40